language: c

sudo: false

os:
    - linux
    - osx

env:
  global:
    - CONDA_DEPENDENCIES="jinja2 cython"
  matrix:
    - PYTHON_VERSION=3.5

install:

    # Install Montage
    - wget http://montage.ipac.caltech.edu/workspace/MontageLib_03Sep16.tar.gz
    - tar xvzf MontageLib_03Sep16.tar.gz
    - cd Montage
    - make
    - cd ..

    # Install Python and dependencies
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:

    - python validate_json.py

    - cd cython
    - python parse.py

    # DEBUG
    - cat montage_direct/wrappers.pxd
    - cat montage_direct/_wrappers.pyx
    - cat montage_direct/main.pyx

    - python setup.py build_ext --inplace
    - python example.py
